apiVersion: apps/v1
kind: Deployment
metadata:
  name: yoda-insurance-microservice1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yoda-insurance-microservice1
  template:
    metadata:
      labels:
        app: yoda-insurance-microservice1
    spec:
      containers:
      - name: yoda-insurance-microservice1
        image: patelanil2061993/yoda-insurance-microservice1:latest
        ports:
        - containerPort: 8080
