apiVersion: v1
kind: Service
metadata:
  name: yoda-insurance-service
spec:
  type: LoadBalancer
  selector:
    app: yoda-insurance-microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
